version: '3.7'
services:
  web:
    container_name: web
    build:
      context: .
      dockerfile: ./docker/nginx/local/Dockerfile
    ### 上のビルドでできたイメージの名前を設定
    image: toranomaki-sample/nginx:latest
    restart: always
    ports:
      - '81:80'
      - '444:443'
    volumes:
      - ./docker/nginx/local/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app

  app:
    container_name: app
    build:
      context: .
      dockerfile: ./docker/app/local/Dockerfile
    ### 上のビルドでできたイメージの名前を設定
    image: toranomaki-sample/app:latest
    ports:
      - '8080:8080'
    tty: true
    volumes:
      - .:/srv
      - ./toranomaki-sample-impl/target/toranomaki-sample.jar:/app.jar
    working_dir: /srv
    expose:
      - 8080

  db:
    image: mysql:8.0.30
    container_name: mysql
    ### db設定
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test_database
      MYSQL_USER: user
      MYSQL_PASSWORD: passw0rd
    ### コマンドで設定
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
    volumes:
      - ./docker/db/data:/var/lib/mysql
      - ./docker/db/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./docker/db/sql:/docker-entrypoint-initdb.d
    ports:
      - '3306:3306'
