#Required
openapi: "3.0.3"

#Required
info:
  title: OAS Sample API
  description: 虎の巻用
  version: "1.0"

servers:
  - url: https://piyopiyo.com/sample
    description: 開発
  - url: https://hogehoge.com/sample
    description: 本番

#Required
paths:
  /sample:
    post:
      summary: Sample API
      parameters:
        - in: query
          name: sampleQuery
          description: クエリ
          required: true
          schema:
            $ref: "./schema/parameter/queryParam.yaml#/components/schemas/queryParam"
        - in: header
          name: SAMPLE-HEADER
          description: ヘッダー
          required: true
          schema:
            $ref: "./schema/parameter/headerParam.yaml#/components/schemas/headerParam"
      requestBody:
        required: true
        content:
          "application/json":
            schema:
              $ref: "./schema/request/requestBody.yaml#/components/schemas/SampleRequestBody"
      responses:
        "200":
          description: "Success."
          content:
            application/json:
              schema:
                $ref: "./schema/response/responseBody.yaml#/components/schemas/SampleResponseBody"
  ## テスト確認用API
  /test/post:
    post:
      summary: POST Test API
      parameters:
        - in: query
          name: query
          required: true
          schema:
            type: string
        - in: header
          name: TEST-HEADER
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          "application/json":
            schema:
              type: object
              required:
                - name
              properties:
                name:
                  type: string
                age:
                  type: integer
      responses:
        "200":
          description: "Success."
          content:
            application/json:
              schema:
                type: object
                properties:
                  name:
                    type: string
  /test/get:
    get:
      summary: GET Test API
      parameters:
        - in: query
          name: name
          required: true
          schema:
            type: string
      responses:
        "200":
          description: "Success."
          content:
            "application/json":
              schema:
                type: object
                properties:
                  name:
                    type: string
                  age:
                    type: integer
                    format: int32
                  query:
                    type: string
                  header:
                    type: string
  /test/delete:
    delete:
      summary: DELETE Test API
      parameters:
        - in: query
          name: name
          required: true
          schema:
            type: string
      responses:
        "200":
          description: "Success."
          content:
            "application/json":
              schema:
                type: object
                properties:
                  message:
                    type: string

externalDocs:
  description: DB定義などのリンク
  url: https://fugagaga.com/db